version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb+srv://freddyfrank69:hoang1337@pbl.d6c3slv.mongodb.net/?retryWrites=true&w=majority&appName=PBL
      - JWT_SECRET=hoang1337
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 